sudo: required
dist: xenial

script:
    - set -e
    - docker-compose build
    - docker-compose up -d
    - set +e
    - docker exec $(docker container ls -f name=client -q) npm audit
    - docker exec $(docker container ls -f name=server -q) npm audit

after_script:
- docker-compose down