version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/data
    environment:
      - API_URL=server:8081

  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    depends_on: 
      - db
    environment:
      - PORT=8081
      - DATABASE_URL=db:27017
    
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db